debug=false
logging.level.root=WARN
#logging.level.org.springframework.data.rest=ERROR
#logging.level.se.uu.ebc.bemanning=ERROR
logging.level.org.springframework=ERROR
logging.level.se.uu.ebc.bemanning=ERROR
logging.path=/tmp/bemanning
#
bemanning.environment.dev=false
bemanning.environment.dev.cas.on=true
#
spring.datasource.url=jdbc\:mariadb\://localhost\:3306/bemanning?useLegacyDatetimeCode=false&serverTimezone=CET
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
management.endpoint.restart.enabled=true
management.endpoint.shutdown.enabled=false
endpoints.shutdown.enabled=false
#
bemanning.base.url=@bemanning.baseurl@
