debug=false
logging.level.root=WARN
logging.level.org.springframework.data.rest=ERROR
logging.level.se.uu.ebc.bemanning=ERROR
logging.path=/tmp/bemanning
#
bemanning.environment.dev=false
bemanning.environment.dev.cas.on=true
#
management.endpoint.restart.enabled=true
management.endpoint.shutdown.enabled=false
endpoints.shutdown.enabled=false
spring.devtools.restart.enabled=false
#
bemanning.base.url=@bemanning.baseurl@
#
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
#
spring.datasource.username=@jdbc.username.prod@
spring.datasource.password=@jdbc.password.prod@
#
